name: Preprocess Attrition

on:
  push:
    branches:
      - main

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Setup Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run preprocessing script & create folder
        run: |
          cd ./Preprocessing
          python automate_Boy_Hendrawan.py

      - name: Save output dataset to repo
        run: |
          cd ./Preprocessing
          git config --global user.name "${{ secrets.username }}"
          git config --global user.email "${{ secrets.email }}"
          git remote set-url origin https://x-access-token:${{ secrets.token }}@github.com/${{ github.repository }}.git
          git add clean_dataset/*.csv pipeline/*.joblib

          # Only commit if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Save output from preprocessing pipeline"
            git push origin main
          fi
